# This is the configuration file for your local development environment. By
# default, it runs a single server on port 8080. To set up your server, you will
# need to add the name of the database you are connecting to and the user name.
# The password for the database is stored in the config/passwords.yaml.
#
# When running your server locally, the server ports are the same as the public
# facing ports.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: localhost
  publicPort: 8080
  publicScheme: http

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: http

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: http

# This is the database setup for your server.
database:
  host: localhost
  port: 8090
  name: lg_tribe
  user: postgres
  password: "rQwVtZc4XySdngIwEdVpapgBFFx6P9CJ# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'ZvFEWyrI3OGkEj15RNRAbPAtRN9Bdlcu'
  redis: 'ughEyj-wJeucmQlB6TKtWLUHLKViS3cV'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'QI_M7QsUHbEolL8OenSvlV0gBrHh-QNO'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: 'use_new_safe_created_password'
  serviceSecret: 'use_new_safe_created_password-5G3WKCtl'

# Passwords used in production mode.
production:
  database: 'use_new_safe_created_password'
  serviceSecret: 'ew9-use_new_safe_created_password'
"
  #requireSsl: true # defaults to false
  #isUnixSocket: true # defaults to false

# This is the setup for Redis.
redis:
  enabled: false
  host: localhost
  port: 8091
  #user: # defaults to empty

maxRequestSize: 524288 # The maximum size of requests allowed in bytes

sessionLogs:
  persistentEnabled: true
  consoleEnabled: true
