services:
  # Development services
  postgres:
    image: postgres:16.3
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lg_tribe
      POSTGRES_PASSWORD: "rQwVtZc4XySdngIwEdVpapgBFFx6P9CJ"
    volumes:
      - lg_tribe_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "QPpBkCGT0Z0OOO-dyzt3cCkWi-iuoE_e"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: postgres:16.3
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lg_tribe_test
      POSTGRES_PASSWORD: "Gf5AqD20RrtmsAWl7acccSqV3kshsHKq"
    volumes:
      - lg_tribe_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "rJH-de5IHR4G2Jckbo2qg6K9-LBbGYfV"
    environment:
      - REDIS_REPLICATION_MODE=master

      
volumes:
  lg_tribe_data:
  lg_tribe_test_data:
