name: lg_tribe_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: 3.8.1

dependencies:
  serverpod: 2.9.1
  bcrypt: ^1.1.3
  serverpod_flutter: 2.9.1

dev_dependencies:
  lints: ^6.0.0
  test: '^1.24.2'
  serverpod_test: 2.9.1

